# Generated by Django 3.2.9 on 2021-11-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='fecha',
            field=models.DateField(),
        ),
    ]
