# Generated by Django 3.2.9 on 2021-11-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0002_alter_farmacia_local_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='local_telefono',
            field=models.CharField(max_length=255),
        ),
    ]
