# Generated by Django 3.2.9 on 2021-11-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0003_alter_farmacia_local_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='local_id',
            field=models.CharField(max_length=255),
        ),
    ]
